export const type ={
    BLOCK_CREATE_REQUEST : 'BLOCK_CREATE_REQUEST',
    BLOCK_CREATE_SUCCESS : 'BLOCK_CREATE_SUCCESS',
    BLOCK_CREATE_FAILURE : 'BLOCK_CREATE_FAILURE',

    BLOCK_LIST_REQUEST : 'BLOCK_LIST_REQUEST',
    BLOCK_LIST_SUCCESS : 'BLOCK_LIST_SUCCESS',
    BLOCK_LIST_FAILURE : 'BLOCK_LIST_FAILURE',

    BLOCK_EDIT_REQUEST : 'BLOCK_EDIT_REQUEST',
    BLOCK_EDIT_SUCCESS : 'BLOCK_EDIT_SUCCESS',
    BLOCK_EDIT_FAILURE : 'BLOCK_EDIT_FAILURE',

    BLOCK_DELETE_REQUEST : 'BLOCK_DELETE_REQUEST',
    BLOCK_DELETE_SUCCESS : 'BLOCK_DELETE_SUCCESS',
    BLOCK_DELETE_FAILURE : 'BLOCK_DELETE_FAILURE',
} 