export const type = {

    CHANNEL_CREATE_REQUEST : 'CHANNEL_CREATE_REQUEST',
    CHANNEL_CREATE_SUCCESS : 'CHANNEL_CREATE_SUCCESS',
    CHANNEL_CREATE_FAILURE : 'CHANNEL_CREATE_FAILURE',

    CHANNEL_GET_REQUEST : 'CHANNEL_GET_REQUEST',
    CHANNEL_GET_SUCCESS : 'CHANNEL_GET_SUCCESS',
    CHANNEL_GET_FAILURE : 'CHANNEL_GET_FAILURE',

    CHANNEL_EDIT_REQUEST   : 'CHANNEL_EDIT_REQUEST',
    CHANNEL_EDIT_SUCCESS   : 'CHANNEL_EDIT_SUCCESS',
    CHANNEL_EDIT_FAILURE   : 'CHANNEL_EDIT_FAILURE',

    CHANNEL_DELETE_REQUEST : 'CHANNEL_DELETE_REQUEST',
    CHANNEL_DELETE_SUCCESS : 'CHANNEL_DELETE_SUCCESS',
    CHANNEL_DELETE_FAILURE : 'CHANNEL_DELETE_FAILURE',
    CHANNEL_DELETE_RESET : 'CHANNEL_DELETE_RESET'
}