export const type = {
    DIALOGUE_CHECK_REQUEST : 'DIALOGUE_CHECK_REQUEST', 
    DIALOGUE_CHECK_SUCCESS : 'DIALOGUE_CHECK_SUCCESS', 
    DIALOGUE_CHECK_FAILURE : 'DIALOGUE_CHECK_FAILURE', 
    DIALOGUE_CHECK_RESET   : 'DIALOGUE_CHECK_RESET', 

    DIALOGUE_BLOCK_REQUEST : 'DIALOGUE_BLOCK_REQUEST', 
    DIALOGUE_BLOCK_SUCCESS : 'DIALOGUE_BLOCK_SUCCESS', 
    DIALOGUE_BLOCK_FAILURE : 'DIALOGUE_BLOCK_FAILURE', 
    DIALOGUE_BLOCK_RESET   : 'DIALOGUE_BLOCK_RESET', 

    DIALOGUE_DELETE_RECORDS_REQUEST : 'DIALOGUE_DELETE_RECORDS_REQUEST', 
    DIALOGUE_DELETE_RECORDS_SUCCESS : 'DIALOGUE_DELETE_RECORDS_SUCCESS', 
    DIALOGUE_DELETE_RECORDS_FAILURE : 'DIALOGUE_DELETE_RECORDS_FAILURE', 
}