export const type = {
    SEQUENCE_LIST_REQUEST : 'SEQUENCE_LIST_REQUEST',
    SEQUENCE_LIST_SUCCESS : 'SEQUENCE_LIST_SUCCESS',
    SEQUENCE_LIST_FAIL : 'SEQUENCE_LIST_FAIL',

    SEQUENCE_CREATE_REQUEST : 'SEQUENCE_CREATE_REQUEST',
    SEQUENCE_CREATE_SUCCESS : 'SEQUENCE_CREATE_SUCCESS',
    SEQUENCE_CREATE_FAIL : 'SEQUENCE_CREATE_FAIL',

    SEQUENCE_REMOVE_REQUEST : 'SEQUENCE_REMOVE_REQUEST',
    SEQUENCE_REMOVE_SUCCESS : 'SEQUENCE_REMOVE_SUCCESS',
    SEQUENCE_REMOVE_FAIL : 'SEQUENCE_REMOVE_FAIL',
}
