export const type = {
    ADD_TIMED_BLOCK_REQUEST: 'ADD_TIMED_BLOCK_REQUEST',
    ADD_TIMED_BLOCK_SUCCESS: 'ADD_TIMED_BLOCK_SUCCESS',
    ADD_TIMED_BLOCK_FAIL   : 'ADD_TIMED_BLOCK_FAIL',
    ADD_TIMED_BLOCK_RESET   : 'ADD_TIMED_BLOCK_RESET',

    LIST_TIMED_BLOCK_REQUEST: 'LIST_TIMED_BLOCK_REQUEST',
    LIST_TIMED_BLOCK_SUCCESS: 'LIST_TIMED_BLOCK_SUCCESS',
    LIST_TIMED_BLOCK_FAIL   : 'LIST_TIMED_BLOCK_FAIL',
    LIST_TIMED_BLOCK_RESET   : 'LIST_TIMED_BLOCK_RESET',

    LIST_TIMED_DIALOGUE_BLOCK_REQUEST: 'LIST_TIMED_DIALOGUE_BLOCK_REQUEST',
    LIST_TIMED_DIALOGUE_BLOCK_SUCCESS: 'LIST_TIMED_DIALOGUE_BLOCK_SUCCESS',
    LIST_TIMED_DIALOGUE_BLOCK_FAIL   : 'LIST_TIMED_DIALOGUE_BLOCK_FAIL',
    LIST_TIMED_DIALOGUE_BLOCK_RESET   : 'LIST_TIMED_DIALOGUE_BLOCK_RESET',

    TOGGLE_TIMED_BLOCK_REQUEST: 'TOGGLE_TIMED_BLOCK_REQUEST',
    TOGGLE_TIMED_BLOCK_SUCCESS: 'TOGGLE_TIMED_BLOCK_SUCCESS',
    TOGGLE_TIMED_BLOCK_FAIL   : 'TOGGLE_TIMED_BLOCK_FAIL',
    TOGGLE_TIMED_BLOCK_RESET   : 'TOGGLE_TIMED_BLOCK_RESET',

    REMOVE_TIMED_BLOCK_REQUEST: 'REMOVE_TIMED_BLOCK_REQUEST',
    REMOVE_TIMED_BLOCK_SUCCESS: 'REMOVE_TIMED_BLOCK_SUCCESS',
    REMOVE_TIMED_BLOCK_FAIL   : 'REMOVE_TIMED_BLOCK_FAIL',
    REMOVE_TIMED_BLOCK_RESET   : 'REMOVE_TIMED_BLOCK_RESET',
}