export const type = {
    ADD_TIMED_BLOCK_REQUEST: 'ADD_TIMED_BLOCK_REQUEST',
    ADD_TIMED_BLOCK_SUCCESS: 'ADD_TIMED_BLOCK_SUCCESS',
    ADD_TIMED_BLOCK_FAIL   : 'ADD_TIMED_BLOCK_FAIL',
    ADD_TIMED_BLOCK_RESET   : 'ADD_TIMED_BLOCK_RESET',

    LIST_BROADCAST_BLOCK_REQUEST: 'LIST_BROADCAST_BLOCK_REQUEST',
    LIST_BROADCAST_BLOCK_SUCCESS: 'LIST_BROADCAST_BLOCK_SUCCESS',
    LIST_BROADCAST_BLOCK_FAIL   : 'LIST_BROADCAST_BLOCK_FAIL',
    LIST_BROADCAST_BLOCK_RESET   : 'LIST_BROADCAST_BLOCK_RESET',

    LIST_TIMED_BLOCK_REQUEST: 'LIST_TIMED_BLOCK_REQUEST',
    LIST_TIMED_BLOCK_SUCCESS: 'LIST_TIMED_BLOCK_SUCCESS',
    LIST_TIMED_BLOCK_FAIL   : 'LIST_TIMED_BLOCK_FAIL',
    LIST_TIMED_BLOCK_RESET   : 'LIST_TIMED_BLOCK_RESET',

    REMOVE_TIMED_BLOCK_REQUEST: 'REMOVE_TIMED_BLOCK_REQUEST',
    REMOVE_TIMED_BLOCK_SUCCESS: 'REMOVE_TIMED_BLOCK_SUCCESS',
    REMOVE_TIMED_BLOCK_FAIL   : 'REMOVE_TIMED_BLOCK_FAIL',
    REMOVE_TIMED_BLOCK_RESET   : 'REMOVE_TIMED_BLOCK_RESET',
}