export const type = {
    WRITERS_LIST_REQUEST  : 'WRITERS_LIST_REQUEST',
    WRITERS_LIST_SUCCESS  : 'WRITERS_LIST_SUCCESS',
    WRITERS_LIST_FAILURE  : 'WRITERS_LIST_FAILURE',

    WRITERS_CHANNELS_REQUEST  : 'WRITERS_CHANNELS_REQUEST',
    WRITERS_CHANNELS_SUCCESS  : 'WRITERS_CHANNELS_SUCCESS',
    WRITERS_CHANNELS_FAILURE  : 'WRITERS_CHANNELS_FAILURE',

    WRITER_LOGIN_REQUEST  : 'WRITER_LOGIN_REQUEST',
    WRITER_LOGIN_SUCCESS  : 'WRITER_LOGIN_SUCCESS',
    WRITER_LOGIN_FAILURE  : 'WRITER_LOGIN_FAILURE',

    WRITER_CREATE_REQUEST : 'WRITER_CREATE_REQUEST',
    WRITER_CREATE_SUCCESS : 'WRITER_CREATE_SUCCESS',
    WRITER_CREATE_FAILURE : 'WRITER_CREATE_FAILURE',
    WRITER_CREATE_RESET   : 'WRITER_CREATE_RESET ',

    WRITER_INFO_REQUEST   : 'WRITER_INFO_REQUEST',
    WRITER_INFO_SUCCESS   : 'WRITER_INFO_SUCCESS',
    WRITER_INFO_FAILURE   : 'WRITER_INFO_FAILURE',
    WRITER_INFO_RESET     : 'WRITER_INFO_RESET',

    WRITER_INFO_BY_ID_REQUEST   : 'WRITER_INFO_BY_ID_REQUEST',
    WRITER_INFO_BY_ID_SUCCESS   : 'WRITER_INFO_BY_ID_SUCCESS',
    WRITER_INFO_BY_ID_FAILURE   : 'WRITER_INFO_BY_ID_FAILURE',
    WRITER_INFO_BY_ID_RESET   : 'WRITER_INFO_BY_ID_RESET',

    WRITER_EDIT_REQUEST   : 'WRITER_EDIT_REQUEST',
    WRITER_EDIT_SUCCESS   : 'WRITER_EDIT_SUCCESS',
    WRITER_EDIT_FAILURE   : 'WRITER_EDIT_FAILURE',

    WRITER_LOGOUT_REQUEST  : 'WRITER_LOGOUT_REQUEST',
    WRITER_LOGOUT_SUCCESS  : 'WRITER_LOGOUT_SUCCESS',
    WRITER_LOGOUT_FAILURE  : 'WRITER_LOGOUT_FAILURE',

    WRITER_BLOCK_REQUEST   : 'WRITER_BLOCK_REQUEST',
    WRITER_BLOCK_SUCCESS   : 'WRITER_BLOCK_SUCCESS',
    WRITER_BLOCK_FAILURE   : 'WRITER_BLOCK_FAILURE',

    WRITER_DELETE_REQUEST   : 'WRITER_DELETE_REQUEST',
    WRITER_DELETE_SUCCESS   : 'WRITER_DELETE_SUCCESS',
    WRITER_DELETE_FAILURE   : 'WRITER_DELETE_FAILURE',
    WRITER_DELETE_RESET     : 'WRITER_DELETE_RESET',

    WRITER_SUBSCRIBE_REQUEST   : 'WRITER_SUBSCRIBE_REQUEST',
    WRITER_SUBSCRIBE_SUCCESS   : 'WRITER_SUBSCRIBE_SUCCESS',
    WRITER_SUBSCRIBE_FAILURE   : 'WRITER_SUBSCRIBE_FAILURE',

    WRITER_UNSUBSCRIBE_REQUEST   : 'WRITER_UNSUBSCRIBE_REQUEST',
    WRITER_UNSUBSCRIBE_SUCCESS   : 'WRITER_UNSUBSCRIBE_SUCCESS',
    WRITER_UNSUBSCRIBE_FAILURE   : 'WRITER_UNSUBSCRIBE_FAILURE',

}