export const CHAT_BLOCKS_ADD = 'CHAT_BLOCK_ADD'
export const CHAT_BLOCKS_RESET = 'CHAT_BLOCK_RESET'

export const BROADCAST_BLOCKS_ADD = 'BROADCAST_BLOCK_ADD'
export const BROADCAST_BLOCK_REMOVE = 'BROADCAST_BLOCK_REMOVE'
export const BROADCAST_BLOCKS_RESET = 'BROADCAST_BLOCK_RESET'

export const CHAT_OPS_CREATE = 'CHAT_OPS_CREATE'
export const CHAT_OPS_DELETE = 'CHAT_OPS_DELETE'
export const CHAT_OPS_RESET = 'CHAT_OPS_RESET'
export const CHAT_OPS_ADD_GALLERY_BLOCK = 'CHAT_OPS_ADD_GALLERY_BLOCK'
export const CHAT_OPS_REMOVE_GALLERY_BLOCK = 'CHAT_OPS_REMOVE_GALLERY_BLOCK'
