export const CHAT_BLOCK_CREATE = 'CHAT_BLOCK_CREATE'
export const CHAT_BLOCK_UPDATE = 'CHAT_BLOCK_UPDATE'
export const CHAT_BLOCK_DELETE = 'CHAT_BLOCK_DELETE'
export const CHAT_BLOCK_REARRANGE = 'CHAT_BLOCK_REARRANGE'
export const CHAT_BLOCK_RESET  = 'CHAT_BLOCK_RESET'


export const CHAT_OPS_CREATE = 'CHAT_OPS_CREATE'
export const CHAT_OPS_DELETE = 'CHAT_OPS_DELETE'
export const CHAT_OPS_RESET = 'CHAT_OPS_RESET'
export const CHAT_OPS_ADD_GALLERY_BLOCK = 'CHAT_OPS_ADD_GALLERY_BLOCK'
export const CHAT_OPS_REMOVE_GALLERY_BLOCK = 'CHAT_OPS_REMOVE_GALLERY_BLOCK'
