export const CHAT_BLOCKS_ADD = 'CHAT_BLOCK_ADD'
export const CHAT_BLOCKS_RESET = 'CHAT_BLOCK_RESET'

export const TIMED_BLOCKS_ADD = 'TIMED_BLOCK_ADD'
export const TIMED_BLOCK_REMOVE = 'TIMED_BLOCK_REMOVE'
export const TIMED_BLOCK_TOGGLE = 'TIMED_BLOCK_TOGGLE'
export const TIMED_BLOCKS_RESET = 'TIMED_BLOCK_RESET'

export const CHAT_OPS_CREATE = 'CHAT_OPS_CREATE'
export const CHAT_OPS_DELETE = 'CHAT_OPS_DELETE'
export const CHAT_OPS_RESET = 'CHAT_OPS_RESET'
export const CHAT_OPS_ADD_GALLERY_BLOCK = 'CHAT_OPS_ADD_GALLERY_BLOCK'
export const CHAT_OPS_REMOVE_GALLERY_BLOCK = 'CHAT_OPS_REMOVE_GALLERY_BLOCK'
